name: Docker Image CI

on:
  push:
    branches: [ master ]
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag node_directory_server:${{ github.ref }}
